accessControl:
    enabled: false
appearance:
    closeModalsWithClick: false
    color: white
    colorTransparent: true
    name: A8 - init Lab
plugins:
    _disabled:
    - announcements
    - tracking
    - appkeys
    - discovery
    - errortracking
    - virtual_printer
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1593102540
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1573722900
            _plugins:
                read_until: 1593838800
            _releases:
                read_until: 1594206900
        enabled_channels:
        - _important
    discovery:
        upnpUuid: 22792b30-da29-444b-bc78-6edc82ac5eca
    errortracking:
        unique_id: 35aab4b3-eb01-4799-8a8d-893b32accd41
    psucontrol:
        _config_version: 3
        disconnectOnPowerOff: true
        enablePseudoOnOff: true
        offSysCommand: 'curl -sX PUT -H "Accept: application/json" http://SECRET/api/relay/0
            --data "apikey=SECRET&value=0"'
        onSysCommand: 'curl -sX PUT -H "Accept: application/json" http://SECRET/api/relay/0
            --data "apikey=SECRET&value=1"'
        senseSystemCommand: curl -s 'http://SECRET/api/relay/0?apikey=SECRET'
            | grep -q 1
        sensingMethod: SYSTEM
        switchingMethod: SYSTEM
    slic3r:
        slic3r_engine: /usr/bin/slic3r-prusa3d
    softwareupdate:
        _config_version: 7
    telegram:
        _config_version: 4
        chats: {}
        messages:
            StatusPrinting:
                combined: true
    themeify:
        color:
        -   deletable: false
            enabled: true
            rule: background
            selector: .navbar-inner
            value: gray
        enableCustomization: true
        theme: discoranged
    tracking:
        enabled: false
        events:
            commerror: false
            plugin: false
            pong: false
            printer: false
            printer_safety_check: false
            printjob: false
            slicing: false
            startup: false
            throttled: false
            update: false
printerProfiles:
    default: _default
serial:
    autoconnect: true
    baudrate: 115200
    port: /dev/ttyUSB-a8
server:
    commands:
        serverRestartCommand: ~/restart.sh &
    firstRun: false
    onlineCheck:
        enabled: false
        host: 9.9.9.9
    pluginBlacklist:
        enabled: true
    seenWizards:
        corewizard: 3
        telegram: 1
        tracking: null
slicing:
    defaultProfiles:
        slic3r: slic3r_config_bundle
temperature:
    profiles:
    -   bed: 65
        chamber: null
        extruder: 210
        name: PLA
webcam:
    snapshot: http://127.0.0.1/streamer/a8/snapshot.jpeg
    stream: /streamer/a8/stream.mjpeg
    streamRatio: '4:3'
