accessControl:
    enabled: false
appearance:
    closeModalsWithClick: false
    color: black
    name: i3 Mega - zzaharie
plugins:
    _disabled:
    - announcements
    - tracking
    - discovery
    - errortracking
    - virtual_printer
    - appkeys
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1589460900
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1573722900
            _plugins:
                read_until: 1592110800
            _releases:
                read_until: 1583322300
        enabled_channels:
        - _important
    softwareupdate:
        _config_version: 7
    telegram:
        _config_version: 4
        chats:
            '-1001214843381':
                accept_commands: true
                allow_users: true
                commands:
                    /abort: false
                    /con: false
                    /ctrl: false
                    /dontshutup: true
                    /filament: false
                    /files: false
                    /gif: true
                    /help: false
                    /print: false
                    /settings: false
                    /shutup: true
                    /status: true
                    /supergif: true
                    /sys: false
                    /test: false
                    /togglepause: false
                    /tune: false
                    /upload: false
                    /user: true
                    'No': false
                    'Yes': false
                id: '-1001214843381'
                image: /plugin/telegram/img/static/group.jpg
                new: false
                newUsr: false
                notifications:
                    PrintDone: true
                    PrintFailed: true
                    PrintPaused: true
                    PrintResumed: true
                    PrintStarted: true
                    PrinterShutdown: true
                    PrinterStart: true
                    StatusNotPrinting: false
                    StatusPrinting: false
                    ZChange: true
                private: false
                send_notifications: true
                title: init Lab 3D Printing
                type: SUPERGROUP
            '102104618':
                accept_commands: true
                allow_users: false
                commands:
                    /abort: true
                    /con: true
                    /ctrl: true
                    /dontshutup: true
                    /filament: true
                    /files: true
                    /gif: true
                    /help: false
                    /print: true
                    /settings: true
                    /shutup: true
                    /status: true
                    /supergif: true
                    /sys: true
                    /test: false
                    /togglepause: true
                    /tune: true
                    /upload: true
                    /user: true
                    'No': false
                    'Yes': false
                id: '102104618'
                image: /plugin/telegram/img/static/default.jpg
                new: false
                newUsr: false
                notifications:
                    PrintDone: false
                    PrintFailed: false
                    PrintPaused: false
                    PrintResumed: false
                    PrintStarted: false
                    PrinterShutdown: false
                    PrinterStart: false
                    StatusNotPrinting: false
                    StatusPrinting: false
                    ZChange: false
                private: true
                send_notifications: false
                title: Венцислав - Атанасов - @Slackware
                type: PRIVATE
        debug: true
        fileOrder: true
        messages:
            StatusPrinting:
                combined: true
        token: xxx
    tracking:
        enabled: false
        events:
            commerror: false
            plugin: false
            pong: false
            printer: false
            printer_safety_check: false
            printjob: false
            slicing: false
            startup: false
            throttled: false
            update: false
printerProfiles:
    default: _default
serial:
    baudrate: 250000
    port: /dev/ttyUSB-i3mega
server:
    commands:
        serverRestartCommand: ./restart.sh &
    onlineCheck:
        enabled: false
    pluginBlacklist:
        enabled: true
temperature:
    profiles:
    -   bed: 62
        chamber: null
        extruder: 205
        name: PLA
webcam:
    snapshot: http://127.0.0.1/streamer/i3mega/snapshot.jpeg
    stream: /streamer/i3mega/stream.mjpeg
    streamRatio: '4:3'
