accessControl:
    enabled: false
appearance:
    closeModalsWithClick: false
    color: red
    colorTransparent: true
    name: Mendel - init Lab
plugins:
    _disabled:
    - announcements
    - tracking
    - appkeys
    - discovery
    - errortracking
    - virtual_printer
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1589460900
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1573722900
            _plugins:
                read_until: 1592110800
            _releases:
                read_until: 1583322300
        enabled_channels:
        - _important
    errortracking:
    gcodeviewer:
        _config_version: 1
    psucontrol:
        _config_version: 3
        disconnectOnPowerOff: true
        enablePseudoOnOff: true
        offSysCommand: 'curl -sX PUT -H "Accept: application/json" http://SECRET/api/relay/0
            --data "apikey=SECRET&value=0"'
        onSysCommand: 'curl -sX PUT -H "Accept: application/json" http://SECRET/api/relay/0
            --data "apikey=SECRET&value=1"'
        senseSystemCommand: curl -s 'http://SECRET/api/relay/0?apikey=SECRET'
            | grep -q 1
        sensingMethod: SYSTEM
        switchingMethod: SYSTEM
    slic3r:
        slic3r_engine: /usr/bin/slic3r-prusa3d
    softwareupdate:
        _config_version: 8
    telegram:
        _config_version: 5
        chats:
            '-1001214843381':
                accept_commands: true
                allow_users: true
                commands:
                    /abort: false
                    /con: false
                    /ctrl: false
                    /dontshutup: true
                    /filament: false
                    /files: false
                    /gif: true
                    /print: false
                    /settings: false
                    /shutup: true
                    /status: true
                    /supergif: true
                    /sys: false
                    /togglepause: false
                    /tune: false
                    /upload: false
                    /user: true
                id: '-1001214843381'
                image: /plugin/telegram/img/static/group.jpg
                new: false
                newUsr: false
                notifications:
                    PrintDone: true
                    PrintFailed: true
                    PrintPaused: true
                    PrintResumed: true
                    PrintStarted: true
                    PrinterShutdown: true
                    PrinterStart: true
                    StatusNotPrinting: false
                    StatusPrinting: false
                    ZChange: true
                    plugin_pause_for_user_event_notify: false
                private: false
                send_notifications: true
                title: init Lab 3D Printing
                type: SUPERGROUP
            '102104618':
                accept_commands: true
                allow_users: false
                commands:
                    /abort: true
                    /con: true
                    /ctrl: true
                    /dontshutup: true
                    /filament: true
                    /files: true
                    /gif: true
                    /print: true
                    /settings: true
                    /shutup: true
                    /status: true
                    /supergif: true
                    /sys: true
                    /togglepause: true
                    /tune: true
                    /upload: true
                    /user: true
                id: '102104618'
                image: /plugin/telegram/img/static/default.jpg
                new: false
                newUsr: false
                notifications:
                    PrintDone: false
                    PrintFailed: false
                    PrintPaused: false
                    PrintResumed: false
                    PrintStarted: false
                    PrinterShutdown: false
                    PrinterStart: false
                    StatusNotPrinting: false
                    StatusPrinting: false
                    ZChange: false
                    plugin_pause_for_user_event_notify: false
                private: true
                send_notifications: false
                title: Венцислав - Атанасов - @Slackware
                type: PRIVATE
            '402093617':
                accept_commands: true
                allow_users: false
                commands:
                    /abort: false
                    /con: false
                    /ctrl: false
                    /dontshutup: false
                    /filament: false
                    /files: false
                    /gif: false
                    /print: false
                    /settings: false
                    /shutup: false
                    /status: false
                    /supergif: false
                    /sys: false
                    /togglepause: false
                    /tune: false
                    /upload: false
                    /user: false
                id: '402093617'
                image: /plugin/telegram/img/static/default.jpg
                new: false
                newUsr: false
                notifications:
                    PrintDone: false
                    PrintFailed: false
                    PrintPaused: false
                    PrintResumed: false
                    PrintStarted: false
                    PrinterShutdown: false
                    PrinterStart: false
                    StatusNotPrinting: false
                    StatusPrinting: false
                    ZChange: false
                    plugin_pause_for_user_event_notify: false
                private: true
                send_notifications: false
                title: 'T - T - '
                type: PRIVATE
        fileOrder: true
        messages:
            StatusPrinting:
                combined: true
        token: SECRET
    themeify:
        color:
        -   deletable: false
            enabled: true
            rule: background
            selector: .navbar-inner
            value: rgba(255, 70, 70, .3)
        enableCustomization: true
        theme: discoranged
    tracking:
        enabled: false
        events:
            commerror: false
            plugin: false
            pong: false
            printer: false
            printer_safety_check: false
            printjob: false
            slicing: false
            startup: false
            throttled: false
            update: false
printerProfiles:
    default: _default
serial:
    additionalPorts:
    - /dev/3dprinter-mendel
    baudrate: 115200
    blacklistedPorts:
    - /dev/ttyUSB*
server:
    commands:
        serverRestartCommand: ~/restart.sh &
    firstRun: false
    onlineCheck:
        enabled: false
    pluginBlacklist:
        enabled: true
    seenWizards:
        corewizard: 3
        telegram: 1
        tracking: null
temperature:
    profiles:
    -   bed: 80
        chamber: null
        extruder: 210
        name: PLA
webcam:
    snapshot: http://127.0.0.1/streamer/mendel/snapshot.jpeg
    stream: /streamer/mendel/stream.mjpeg
    streamRatio: '4:3'
